config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'contacts#new'

  get 'contacts/create'

  get 'about' => 'about#index'

  namespace :admin do
  get 'login' => 'sessions#new', :as => 'login'
  end

  namespace :admin do
  get 'logout' => 'sessions#destroy', :as => 'logout'
  end

  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
  get 'users/create'
  end

  namespace :admin do
  get 'users/edit'
  end

  namespace :admin do
  get 'users/update'
  end

  namespace :admin do
  get 'users/destroy'
  end

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/show'
  end

  namespace :admin do
  get 'comments/destroy'
  end

  get 'comments/new'

  namespace :admin do
  get 'categories/new'
  end

  namespace :admin do
  get 'categories/create'
  end

  namespace :admin do
  get 'categories/edit'
  end

  namespace :admin do
  get 'categories/update'
  end

  namespace :admin do
  get 'categories/destroy'
  end

  namespace :admin do
  get 'categories/index'
  end

  namespace :admin do
  get 'categories/show' => 'categories#index'
  end

  get 'categories/show'

  namespace :admin do
  get 'posts/new'
  end

  namespace :admin do
  get 'posts/create'
  end

  namespace :admin do
  get 'posts/edit'
  end

  namespace :admin do
  get 'posts/update'
  end

  namespace :admin do
  get 'posts/destroy'
  end

  namespace :admin do
  get 'posts/index'
  end

  namespace :admin do
  get 'posts/show'
  end

  get 'posts/index'

  get 'posts/show'

  resources :posts, :categories
  resources "contacts", only: [:new, :create]
  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end
  resources :posts do
    resources :comments
  end
  
  root 'posts#index'
  
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
	validates :name, presence: true
	def self.search(query)
		where("name like ?", "%#{query}%")
	end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_filter :verify_logged_in
  
  def new
    @page_title = 'Add Category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category Created'
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'Category Updated'
      redirect_to admin_categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = 'Category Removed'
    redirect_to admin_categories_path
    
  end

  def index
    if params[:search]
      @categories = Category.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    else
      @categories = Category.all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    end
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  	@category = Category.find(params[:id])
  	@categories = Category.all
  	@posts = @category.posts
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<div id="posts-index">
  <% if @posts.exists?  %>
    <%@posts.each_slice(2) do |post| %>
      <div class="row">
        <% post.each do |post| %>
          <div class="col-md-6">
            <div class="post">
              <%= image_tag post.image.url, width: '100%' %>
              <div class="post-content">
                <h3><%= post.title %></h3>
                <small>posted by <%= post.user.name %> on <%= post.created_at.to_time.strftime('%B %e at %l:%M %p')%></small>
                <%= raw post.body.truncate(200) %>
                <%= link_to 'Read More', post_path(post), class:'btn btn-primary' %>
              </div><!-- Epost-content -->
            </div><!-- post -->
          </div><!-- col-md-6 -->
        <% end %><!-- END each-->
      </div><!-- index-->
    <% end %><!-- END each_slice-->
  <% else %>
  <p>No posts in this category yet</p>
  <% end %><!-- END if-->
</div><!-- posts-index-->